default: &default
  adapter: postgresql
  pool: 5

development:
  <<: *default
  encoding: utf8
  database: shiny_dev
  host: localhost
  pool: 5
  username: shiny
  password: shiny_secret 

production:
  <<: *default
  database: largobox_shiny58
  encoding: utf8
  username: largobox_shiny58
  password: 7wmXwPCHz
